export const subjects = [
  {
    id: 'power-plant',
    title: 'Power Plant Engineering',
    shortTitle: 'Power Plant',
    description: 'Thermodynamics, fluids, heat transfer, pumps, turbines, and plant operations.',
    examContext: 'Aligned with the PRC-style Power Plant Engineering bucket for ME review.',
    accent: '#58cc02',
  },
  {
    id: 'mathematics',
    title: 'Mathematics',
    shortTitle: 'Mathematics',
    description: 'Engineering math symbols used in formulas, rate changes, angles, and rotations.',
    examContext: 'A focused track for symbols that appear repeatedly in problem-solving steps.',
    accent: '#1cb0f6',
  },
  {
    id: 'machine-design',
    title: 'Machine Design, Materials & Shop Practice',
    shortTitle: 'Machine Design',
    description: 'Stress, strain, shafts, beams, fasteners, columns, and manufacturing terms.',
    examContext: 'Combines machine design, materials, and shop practice into one pilot subject.',
    accent: '#ce82ff',
  },
];

export const greekLetters = [
  {
    id: 'alpha',
    symbol: 'α',
    name: 'Alpha',
    pronunciation: 'AL-fuh',
    primaryMeaning: 'Coefficient of thermal expansion',
    usedIn: 'Thermal expansion of rails, rods, pipes, and machine parts',
    detail: 'Often appears in ΔL = αLΔT to estimate expansion or contraction from temperature change.',
    subjectIds: ['power-plant', 'machine-design'],
    difficulty: 1,
  },
  {
    id: 'delta-uppercase',
    symbol: 'Δ',
    name: 'Delta, uppercase',
    pronunciation: 'DEL-tuh',
    primaryMeaning: 'Change in a quantity',
    usedIn: 'ΔT, ΔL, ΔP, ΔU, and other before-and-after quantities',
    detail: 'Uppercase delta is the all-purpose marker for finite change in engineering problems.',
    subjectIds: ['power-plant', 'mathematics', 'machine-design'],
    difficulty: 1,
  },
  {
    id: 'delta-lowercase',
    symbol: 'δ',
    name: 'Delta, lowercase',
    pronunciation: 'DEL-tuh',
    primaryMeaning: 'Deflection or small displacement',
    usedIn: 'Beam deflection, shaft displacement, and deformation checks',
    detail: 'Some local examples also use δ for unit weight, so compare the problem context carefully.',
    subjectIds: ['mathematics', 'machine-design'],
    difficulty: 1,
  },
  {
    id: 'gamma',
    symbol: 'γ',
    name: 'Gamma',
    pronunciation: 'GAM-muh',
    primaryMeaning: 'Specific weight or unit weight',
    usedIn: 'Fluid statics, weight density, hydrostatic pressure, and shaft weight problems',
    detail: 'Gamma commonly means weight per unit volume and is related to density through γ = ρg.',
    subjectIds: ['power-plant', 'machine-design'],
    difficulty: 1,
  },
  {
    id: 'sigma',
    symbol: 'σ',
    name: 'Sigma',
    pronunciation: 'SIG-muh',
    primaryMeaning: 'Normal stress',
    usedIn: 'Tension, compression, bending stress, and principal stress',
    detail: 'Sigma is the go-to symbol for stress acting normal to a section area.',
    subjectIds: ['machine-design'],
    difficulty: 1,
  },
  {
    id: 'tau',
    symbol: 'τ',
    name: 'Tau',
    pronunciation: 'TAW',
    primaryMeaning: 'Shear stress',
    usedIn: 'Torsion, punching holes, rivets, welds, and combined stress',
    detail: 'Tau marks stress acting parallel to a surface, especially in shaft and fastener problems.',
    subjectIds: ['machine-design'],
    difficulty: 1,
  },
  {
    id: 'epsilon',
    symbol: 'ε',
    name: 'Epsilon',
    pronunciation: 'EP-si-lon',
    primaryMeaning: 'Normal strain',
    usedIn: 'Stress-strain relationships, elongation, and Poisson’s ratio',
    detail: 'Epsilon is deformation per original length and is dimensionless.',
    subjectIds: ['machine-design'],
    difficulty: 1,
  },
  {
    id: 'nu',
    symbol: 'ν',
    name: 'Nu',
    pronunciation: 'NOO',
    primaryMeaning: 'Poisson’s ratio',
    usedIn: 'Lateral strain, axial strain, dilatation, and elastic material behavior',
    detail: 'Nu relates lateral strain to axial strain when a member is loaded.',
    subjectIds: ['machine-design'],
    difficulty: 1,
  },
  {
    id: 'mu',
    symbol: 'μ',
    name: 'Mu',
    pronunciation: 'MYOO',
    primaryMeaning: 'Coefficient of friction or dynamic viscosity',
    usedIn: 'Dry friction, belts, bearings, lubrication, and fluid-flow problems',
    detail: 'Read the topic first: μ may mean friction in machine design or viscosity in fluids.',
    subjectIds: ['power-plant', 'machine-design'],
    difficulty: 2,
  },
  {
    id: 'rho',
    symbol: 'ρ',
    name: 'Rho',
    pronunciation: 'ROH',
    primaryMeaning: 'Density',
    usedIn: 'Fluid mechanics, thermodynamics, mass calculations, and specific weight',
    detail: 'Rho is mass per unit volume and is often paired with γ = ρg.',
    subjectIds: ['power-plant'],
    difficulty: 2,
  },
  {
    id: 'theta',
    symbol: 'θ',
    name: 'Theta',
    pronunciation: 'THAY-tuh',
    primaryMeaning: 'Angle or angular displacement',
    usedIn: 'Trigonometry, statics, torsion twist, and machine kinematics',
    detail: 'Theta usually marks an angle, including twist angle in shafts.',
    subjectIds: ['mathematics', 'machine-design'],
    difficulty: 2,
  },
  {
    id: 'omega',
    symbol: 'ω',
    name: 'Omega, lowercase',
    pronunciation: 'oh-MAY-guh',
    primaryMeaning: 'Angular velocity',
    usedIn: 'Rotating machinery, dynamics, vibration, pumps, turbines, and flywheels',
    detail: 'Omega is commonly measured in radians per second and links rotation to linear speed.',
    subjectIds: ['power-plant', 'mathematics', 'machine-design'],
    difficulty: 2,
  },
];

export const getLettersForSubject = (subjectId) =>
  greekLetters.filter((letter) => letter.subjectIds.includes(subjectId));
